// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package web

import (
	"gocho/dao"
	"gocho/services"
)

// Injectors from container.go:

func CreateUserHandler() *UserHandler {
	dbConfig := dao.GetDbConfig()
	database := dao.NewSqlxDatabase(dbConfig)
	userDao := dao.NewUserDao(database)
	userService := services.NewUserService(userDao)
	userHandler := NewUserHandler(userService)
	return userHandler
}
